version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 run.py
    volumes:
      - .:/usr/src/app
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=src/run.py
      - FLASK_ENV=development
